---
- name: Install depends
  ansible.builtin.apt:
    name:
      - wireguard
      - iptables
      - cron
    state: latest
    update_cache: true

- name: Enable IPv4 formward
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '#net.ipv4.ip_forward=1'
    line: net.ipv4.ip_forward=1
  notify: Restart sysctl 

- name: Create nat rule after reboot
  ansible.builtin.cron:
    name: "Start nat after reboot"
    special_time: reboot
    job: "/sbin/iptables -A POSTROUTING -t nat -j MASQUERADE"
  notify: Activate nat

- name: Disable wg before editing
  ansible.builtin.systemd_service:
    name: wg-quick@wg.service
    enabled: false
    state: stopped

- name: Genirate wireguard configuration file
  template:
    src: wg.conf.j2
    dest: /etc/wireguard/wg.conf

- name: Enable wg after editing
  ansible.builtin.systemd_service:
    name: wg-quick@wg.service
    enabled: true
    state: started