- name: Install depends
  ansible.builtin.apt:
    name:
      - gcc
      - make
    state: latest
    update_cache: true

- name        : Unarchive a file from Internet
  ansible.builtin.unarchive:
    src       : https://github.com/z3APA3A/3proxy/archive/0.9.3.tar.gz
    dest      : /tmp/
    remote_src: yes

- name: Build 3proxy
  make:
    chdir: /tmp/3proxy-0.9.3
    file: Makefile.Linux