---
- name: Generate .rsc to check and configure capsman
  template:
    src: configure_capsman.rsc.j2
    dest: ./files/tmp/configure_capsman_{{inventory_hostname}}.rsc

- name: Run .rsc script
  command: bash -c "cat ./files/tmp/configure_capsman_{{inventory_hostname}}.rsc |  ssh -i {{ ansible_ssh_private_key_file }} {{ ansible_user }}@{{inventory_hostname}} -T -p 22" 
  register: debug

- name: debug
  debug:
    msg: debug
    
# - name: Delete temp .rsc file
#   file: 
#     path: ./files/tmp/configure_capsman_{{inventory_hostname}}.rsc
#     state: absent