---
- name: Set hostname
  block:
  - name: Generate .rsc to check and set hostname
    template:
      src: set_hostname.rsc.j2
      dest: ./files/tmp/set_hostname_{{inventory_hostname}}.rsc

  - name: Run .rsc script
    shell: bash -c "cat ./files/tmp/set_hostname_{{inventory_hostname}}.rsc |  ssh -i {{ ansible_ssh_private_key_file }} {{ ansible_user }}@{{inventory_hostname}} -T -p 22" 

  # - name: Delete temp .rsc file
  #   file: 
  #     path: ./files/tmp/set_hostname_{{inventory_hostname}}.rsc
  #     state: absent
  when: MIKROTIK_HOSTNAME is defined