---
- name: Generate .rsc to check and set interface lists
  template:
    src: set_access_policy.rsc.j2
    dest: ./files/tmp/set_access_policy_{{inventory_hostname}}.rsc

- name: Run .rsc script
  command: bash -c "cat ./files/tmp/set_access_policy_{{inventory_hostname}}.rsc |  ssh -i {{ ansible_ssh_private_key_file }} {{ ansible_user }}@{{inventory_hostname}} -T -p 22" 

- name: Delete temp .rsc file
  file: 
    path: ./files/tmp/set_access_policy_{{inventory_hostname}}.rsc
    state: absent