---
- name: Generate random password via pwgen
  command: "pwgen -s 19 1"
  register: random_passwd

- debug: var=random_passwd.stdout

- name: Generate .rsc to check and add user
  template:
    src: control_user.rsc.j2
    dest: ./files/tmp/create_user_{{ item.name }}_{{inventory_hostname}}.rsc
  with_items: "{{ MIKROTIK_USERS }}"

- name: Run .rsc script
  command: bash -c "cat ./files/tmp/create_user_{{ item.name }}_{{inventory_hostname}}.rsc |  ssh -i {{ ansible_ssh_private_key_file }} {{ ansible_user }}@{{inventory_hostname}} -T -p 22" 
  with_items: "{{ MIKROTIK_USERS }}"

- name: Delete temp .rsc file
  file: 
    path: ./files/tmp/create_user_{{ item.name }}_{{inventory_hostname}}.rsc 
    state: absent
  with_items: "{{ MIKROTIK_USERS }}"
