---
- name: Generate .rsc to check and add user
  template:
    src: control_user.rsc.j2
    dest: ./files/tmp/create_user_{{inventory_hostname}}.rsc

- name: Run .rsc script
  command: bash -c "cat ./files/tmp/create_user_{{inventory_hostname}}.rsc |  ssh -i {{ ansible_ssh_private_key_file }} {{ ansible_user }}@{{inventory_hostname}} -T -p 22" 

- name: Delete temp .rsc file
  file: 
    path: ./files/tmp/create_user_{{inventory_hostname}}.rsc 
    state: absent
