- name: Configuration credentials MinIO Client
  command: mc alias set {{ item.name }} {{ item.url }} {{ item.access_key }} {{ item.secret_key }}
  no_log: true
  with_items: "{{ MC_CREDENTIALS }}"
  when: 
    - SERVERNAME == item.target and MC_NODE is defined