- name    : Check arm architecture
  set_fact:
    DEFAULT_ARCHITECTURE: arm64
  when    : ("'armv7l' in ansible_architecture") or ("'aarch64' in ansible_architecture")

- name    : Check amd64 architecture
  set_fact:
    DEFAULT_ARCHITECTURE: amd64
  when    : "'x86_64' in ansible_architecture"

- name: Debug
  debug:
    msg: "{{ ansible_architecture }}"

- name: Install depends
  ansible.builtin.apt:
    name:
      - cron
      - nfs-common
    state: latest
    update_cache: true

- name: Download MinIO Client
  get_url:
    url: https://dl.min.io/client/mc/release/linux-{{ DEFAULT_ARCHITECTURE }}/mc
    dest: /usr/local/bin/mc
    mode: '0755'

- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/local/bin/mc
    dest: /usr/bin/mc
    state: link
    mode: 0755

- name: Check version MinIO Client
  command: "mc --version"
  register: mc_version
  changed_when: false

- name: Output version MinIO Client
  debug:
    msg: "{{ mc_version.stdout }}"

- name: Install cron
  ansible.builtin.apt:
    name:
      - cron
    state: latest
    update_cache: true