---
# tasks file for mc

- name         : Install mc
  include_tasks: installation.yaml
  when: MC_INSTALL == true and MC_NODE is defined

- name         : Configuration mc
  include_tasks: configuration.yaml

- name         : Prepare to efs
  include_tasks: efs_backup_preparation.yaml

- name         : Create configuration
  include_tasks: create_configuration.yaml